name: clcherliograph
favicon: null
layout_spectrum: 0.99733
typography_spectrum: 0.75
title: Herliograph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8abfe1'
    - '#030305'
    - '#fe6531'
    - '#b40165'
    - '#fc29b9'
  brandStrength: 0.375
  lightness: 0.4187723654322326
  saturation: 0.08514819317497313
  rhythmicContrast: 0.46596306981518865
purpose: []
