name: clcherliograph
favicon: null
layout_spectrum: 0.49288
typography_spectrum: 0.2776178165804595
title: Herliograph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#949897'
    - '#676b6a'
    - '#382922'
    - '#ffffff'
  brandStrength: 0.0625
  lightness: 0.4187723654322326
  saturation: 0.08514819317497313
  rhythmicContrast: 0.46596306981518865
purpose: []
